changes

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -22,8 +22,9 @@ jobs:
 
       - name: 🔐 Inject .env from GitHub Secret
         run: echo "${{ secrets.ENV_FILE }}" > .env
-
+      
       - name: ✅ Check if secrets are passed
+        shell: bash
         run: |
           if [ -z "${{ secrets.POSTGRES_USER }}" ]; then
             echo "❌ POSTGRES_USER is NOT set"
@@ -47,18 +48,18 @@ jobs:
           fi
 
 
-            - name: 🐳 Docker Compose Up (Build & Run)
-              run: docker-compose up --build -d
+      - name: 🐳 Docker Compose Up (Build & Run)
+        run: docker-compose up --build -d
 
-            - name: 🐘 Show Postgres logs
-              if: always()
-              run: docker logs postgres-db || true
-        
+      - name: 🐘 Show Postgres logs
+        if: always()
+        run: docker logs postgres-db || true
+  
 
-            - name: ✅ Health check (wait then test)
-              run: |
-                sleep 10
-                curl --fail http://localhost || (echo "App failed to start" && exit 1)
+      - name: ✅ Health check (wait then test)
+        run: |
+          sleep 10
+          curl --fail http://localhost || (echo "App failed to start" && exit 1)
 
             
 
